services:
  app:
    image: ghcr.io/langalex/henry:latest
    environment:
      - LETTERMINT_API_TOKEN=""
      - PUBLIC_APP_URL=""
    ports:
      - "4000:4000"
    volumes:
      - db:/db
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:4000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  db:
